<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
$title = 'Edit Post';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<div class="form-group form-inline">

<?php
$form->setAttribute('action', $this->url('post', ['action' => 'edit', 'id' => $id]));
$form->prepare();
?>

<?php
echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
?>
</br>
<?php
echo $this->formRow($form->get('title'));
?>
</br>
<?php
echo $this->formRow($form->get('description'));
?>
</br>
<?php
echo $this->formRow($form->get('category'));
?>
</br>
<?php
echo $this->formSubmit($form->get('submit'));
?>

</div>

<div class="container row mt-4">
	<a href="<?php echo $this->url('post');?>" class="btn btn-info">&laquo BACK</a>
</div>
