<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<div class="jumbotron">
    <h1 class="display-4">Blog Page</h1>
</div>

<div class="row mb-4">
	<a href="<?php echo $this->url('post', ['action' => 'add']);?>" class="btn btn-success">New Post</a>
</div>

<div class="card-deck">
	<table class="table table-hover">
	  <thead>
	    <tr>
	      <th scope="col">ID</th>
	      <th scope="col">Title</th>
	      <th scope="col">Description</th>
	      <th scope="col">Category</th>
	      <th scope="col">Action</th>
	    </tr>
	  </thead>
	  <tbody>

	  <?php if (count($posts)):?>
	  	<?php foreach ($posts as $post):?>
	    <tr>
	      <th scope="row"><?= $post->getId()?></th>
	      <td><?= $post->getTitle()?></td>
	      <td><?= $post->getDescription()?></td>
	      <td class="text-center"><?= $post->getCategory()?></td>
	      <td class="text-center">
	      	<a href="<?php echo $this->url('post', ['action' => 'show', 'id' => $post->getId()]);?>" class="badge bg-success text-light">View</a>
	      	<a href="<?php echo $this->url('post', ['action' => 'edit', 'id' => $post->getId()]);?>" class="badge bg-primary text-light">Edit</a>
	      	<a href="<?php echo $this->url('post', ['action' => 'delete', 'id' => $post->getId()]);?>" class="badge bg-danger text-light">Delete</a>
	      </td>
	    </tr>
	  	<?php endforeach;?>
	  <?php else:?>
	  	<tr>
	  		<td class="text-warning">No data found.</td>
	  	</tr>
	  <?php endif;?>
	  </tbody>
	</table>

</div>
