<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<div class="jumbotron">
    <h1 class="display-4">Welcome to<br>Dev Laboratory <small><span class="font-italic font-sm">managed by<br> Dziamid Harbatsevich</span></small></h1>

    <hr class="my-4">

    <a class="btn btn-primary btn-lg" href="/calendar">
        Check Calendar Page &raquo;
    </a>
</div>

<div class="card-deck">
    <div class="card">
        <h2 class="card-header">Calendar Page</h2>
        <div class="card-body">
            <p>
                You can add a new event on some free of events date in calendar.
            </p>
            <p>
                Then you can subscribe a client with name/email for this event.
            </p>
            <a class="btn btn-primary" href="/calendar">Calendar &raquo;</a>
        </div>
    </div>

    <div class="card">
        <h2 class="card-header">Clients Page</h2>
        <div class="card-body">
            <p>
                Check the list of clients that subscribed for events.
            </p>

            <a class="btn btn-primary" href="/clients">
                Clients &raquo;
            </a>
        </div>
    </div>

    <div class="card">
        <h2 class="card-header">Find this project on GitHub</h2>
        <div class="card-body">

            <a class="btn btn-primary" href="https://github.com/Dziamid-Harbatsevich/zend-lab" target="_blank">This project on GitHub &raquo;</a>
        </div>
    </div>
</div>
