<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<div class="jumbotron">
    <h1 class="display-4">Welcome to<br>Dev Laboratory <small><span class="font-italic font-sm">managed by<br> Dziamid Harbatsevich</span></small></h1>

    <hr class="my-4">

    <a class="btn btn-primary btn-lg" href="/calendar">
        Check Calendar Page &raquo;
    </a>
</div>

<div class="card-deck">
    <div class="card">
        <h2 class="card-header">Calendar Page</h2>
        <div class="card-body">
            <p>
                You can add a new event on some free of events date in calendar.
            </p>
            <p>
                Then you can subscribe a client with name/email for this event.
            </p>
            <a class="btn btn-primary" href="/calendar">Calendar &raquo;</a>
        </div>
    </div>

    <div class="card">
        <h2 class="card-header">Clients Page</h2>
        <div class="card-body">
            <p>
                Check the list of clients that subscribed for events.
            </p>

            <a class="btn btn-primary" href="/clients">
                Clients &raquo;
            </a>
        </div>
    </div>

    <div class="card">
        <h2 class="card-header">This Lab Uses Laminas (Zend) Framework</h2>
        <div class="card-body">
            <p>
                Laminas Project is under active development. If you are
                interested in following the development, you can check
                <a href="https://getlaminas.org/blog/">Laminas dev blog</a>,
                and <a href="https://github.com/issues?utf8=%E2%9C%93&amp;q=is:issue+org:laminas">Laminas issue tracker</a>
                (link requires a GitHub account). This is a great resource
                for staying up to date with the latest developments!
            </p>

            <a class="btn btn-primary" href="https://getlaminas.org/" target="_blank">Laminas Project Portal &raquo;</a>
        </div>
    </div>
</div>
